import type { Metadata } from "next";
import styles from "./page.module.css";
import "../themes/main.scss";
export const metadata: Metadata = {
  title: "techfriar",
  description: "Generated by Ajai kc",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
        <body className={styles.pageBackground}>{children}</body>
    </html>
  );
}
